# Namespace definition

apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
  labels:
    app: zk

---

# Resource limits definition

apiVersion: v1
kind: LimitRange
metadata:
  name: zk-lr
  namespace: zookeeper
  labels:
    app: zk
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 0.5
    defaultRequest:
      memory: 1Gi
      cpu: 0.5
    max:
      memory: 1Gi
      cpu: 0.5
    min:
      memory: 512Mi
      cpu: 0.25
    type: Container

---

# Resource quotas definition

apiVersion: v1
kind: ResourceQuota
metadata:
  name: zk-rq
  namespace: zookeeper 
  labels:
    app: zk
spec:
  hard:
    requests.cpu: 1.5
    requests.memory: 3Gi
    limits.cpu: 2.5
    limits.memory: 5Gi
    pods: 5

---

# Headless Service definition

apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: zookeeper
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk

---

# Exposed service definition

apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: zookeeper
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
    nodePort: 32181
  selector:
    app: zk
  type: NodePort
  externalTrafficPolicy: Local
  externalName: zk.mpt.mp.br

---

# Pod disruption budget definition

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: zookeeper
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1

---

# Pod Stateful Set definition

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: zookeeper
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      namespace: zookeeper
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zk
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - infra  
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: IfNotPresent
        image: "smartlab/zookeeper:3.4.14"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=WARN"
          #--log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: zookeeper
      labels:
        app: zk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
